### ISSUE TITLE
SD card booting disables USB keyboard

### ISSUE THREAD

**Issue by BrianHoldsworth** [IRQsome/NeoYume#6]
NeoYume binary works fine with USB keyboard attached when the binary is stored in the P2-ES flash and the P2 is booted from the flash. Copying the same binary to /_BOOT_P2.BIX on the FAT32-formatted SD card successfully starts up NeoYume, but cannot use the keyboard. I have not been able to try other USB devices yet to see if they also fail when booting from the SD card.

__Update__: This was caused by the slow boot time from the SD card causing the USB keyboard to timeout the connection. Simplest workaround is to simply re-plug the troublesome USB device after booting. Better solution is to instead use the alternative, much faster, SD boot code below.

**Comment by Wuerfel21** [comment]
Should work (and last I tried SD boot + USB, it did work).
Try another keyboard. Or alternatively, try serial download after letting the P2 run for a bit - maybe your keyboard doesn't like that the P2 takes a long time to boot. Or just try hotplugging the keyboard after boot.

Alternatively, use the fastboot stub as _BOOT_P2.BIX to speed up SD booting and see if that changes anything.
```spin
CON _CLKFREQ = 300_000_000
DAT
              org 0
              asmclk
              '' Patch pullup check
              wrlong #0,##$fc5b4 ' not sure why it fails but ok
              '' Move filename into place
              mov $1DC,name+0
              mov $1DD,name+1
              mov $1DE,name+2
              drvh #38 ' Set LED
              call #$fc578
              drvl #38 ' Clear LED if fail
              jmp #$

name          byte "LOADTEST","BIX",0
```
(rename the neoyume binary to LOADTEST. Or change the name in the stub. Whatever)
(also remove/change the LED lines if you're not using a P2EDGE)

**Comment by BrianHoldsworth** [comment]
Seems to be timing/keyboard related, since I confirmed hot-plugging the keyboard works as a simple workaround.

Also, wow! That fastboot stub really speeds up the load A LOT, and also fixes the problem for the keyboard.

I'll confirm these workarounds with my Retro-Bit gamepad when it arrives in a few days.

**Comment by Wuerfel21** [comment]
Yea, probably an issue with your particular keyboard. Then again, I only test with one keyboard through an active PS/2-to-USB converter, maybe that's the actual weird case. Either way, not my fault I think, USB driver's busted.

**Comment by BrianHoldsworth** [comment]
Of course, the supported USB gamepad works fine. I feel like this is a "non-issue", especially because after using the faster SD boot code, I doubt anyone would want to go back to the slower method. My only real suggestion might be to convert this to a "feature request" to include some scripted/idiot-proof way to install the needed binaries to an SD card.

**Comment by Wuerfel21** [comment]
Yea should probably add a note or smth. Then again, I don't think it happens with my keyboard.

**Comment by Wuerfel21** [comment]
@BrianHoldsworth please confirm if this still happens with the current version, a lot has changed with the USB driver.

**Comment by BrianHoldsworth** [comment]
Hi. Wanted to see if I could reproduce any of this weirdness, but cannot build "neoyume_upper.spin2" using latest flexspin. Not sure what I'm doing wrong - seems like something may have changed in the flexspin include directory... See error below along with flexspin version used.

/home/brian/Development/spin2cpp/include/filesys/fatfs/fatfs.cc:434: error: unknown identifier f_sync used in function call
/home/brian/Development/spin2cpp/include/filesys/fatfs/fatfs.cc:434: error: Unknown symbol f_sync
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2023 Total Spectrum Software Inc. and contributors
Version 6.1.8 Compiled on: Jun 17 2023

**Comment by Wuerfel21** [comment]
Oh wow, it really is busted.

**Comment by Wuerfel21** [comment]
@BrianHoldsworth build with this branch: https://github.com/totalspectrum/spin2cpp/pull/392

**Comment by BrianHoldsworth** [comment]
I built using your fork, and tested with my USB keyboard and gamepad. Not seeing the original problem with the keyboard unresponsive. Seems like it works, as I can start a game by pressing "Enter" on the keyboard. But, for some reason, pressing "D" doesn't show the credits screen. Is that expected?

**Comment by Wuerfel21** [comment]
It means D as in the virtual Neo Geo's D button, which is the V key on the keyboard (see readme)

**Comment by BrianHoldsworth** [comment]
Ah, naturally. Seems working!
